acc/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from .views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "account"
urlpatterns = [

    path("login/", LoginView.as_view(template_name="acc/login.html"), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("create/", AccountCreateView.as_view(), name='create'),
    path("detail/<int:pk>", AccountDetailView.as_view(), name='detail'),
    path("update/<int:pk>", AccountUpdateView.as_view(), name='update'),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = "articleapp"

urlpatterns = [
    path("list/", ArticleListView.as_view(), name="list"),
    path("create/", ArticleCreateView.as_view(), name="create"),
    path("detail/<int:pk>", ArticleDetailView.as_view(), name="detail"),
    path("update/<int:pk>", ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="delete"),
]

prog/program/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include("acc.urls")),
                  path('profiles/', include("profileapp.urls")),
                  path('articles/', include("articleapp.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

program/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
                  path("", ArticleListView.as_view(), name="home"),
                  path('admin/', admin.site.urls),
                  path('accounts/', include("acc.urls")),
                  path('profiles/', include("profileapp.urls")),
                  path('articles/', include("articleapp.urls")),
                  path('comments/', include("commentapp.urls")),
                  path('projects/', include("projectapp.urls")),
                  path('subscribes/', include("subscribeapp.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from .views import ProjectCreateView, ProjectListView, ProjectDetailView

app_name = "projectapp"

urlpatterns = [
    path("create/", ProjectCreateView.as_view(), name='create'),
    path("list/", ProjectListView.as_view(), name='list'),
    path("detail/<int:pk>", ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = "subscribeapp"

urlpatterns = [
    path("subscribe/", SubscriptionView.as_view(), name="subscribe"),
    path("list/", SubscriptionListView.as_view(), name="list"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}

<body style="font-family: 'NanumSquareRoundOTFR';">

{% include 'header.html' %}
<hr>
{% block content %}
{% endblock %}
<hr>
{% include "footer.html" %}


</body>
</html>

templates/footer.html
<div class="program_footer">
    <div class="program_footer_button" >
        <span>공지사항</span>
        <span>서비스</span>
        <span>제휴사항</span>
    </div>
    <div class="program_footer_logo">
        <h6>Program</h6>
    </div>
</div>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Title</title>
    <!--bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    {#  google fonts link #}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nerko+One&display=swap" rel="stylesheet">

    {# default css link   #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    {#  google icon  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
          rel="stylesheet">
    <style>
        @font-face {
            font-family: 'NanumSquareRoundOTFB';
            src: local("NanumSquareRoundOTFB"),
            url("{% static 'fonts/NanumSquareRoundOTFB.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareRoundOTFEB';
            src: local("NanumSquareRoundOTFEB"),
            url("{% static 'fonts/NanumSquareRoundOTFEB.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareRoundOTFL';
            src: local("NanumSquareRoundOTFL"),
            url("{% static 'fonts/NanumSquareRoundOTFL.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareRoundOTFR';
            src: local("NanumSquareRoundOTFR"),
            url("{% static 'fonts/NanumSquareRoundOTFR.otf' %}") format("opentype");
        }

    </style>
</head>

templates/header.html
<div class="program_header">
    <div>
        <h1 class="program_logo">Program</h1>
    </div>
    <div class="program_header_navbar">
        <a href="{% url 'articleapp:list' %}" class="program_header_nav">
            <span>Articles</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="program_header_nav">
            <span>Projects</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}" class="program_header_nav">
            <span>Subscriptions</span>
        </a>
        {% if not user.is_authenticated %}
            <a href="{% url 'account:login' %}?next={{ request.path }}" class="program_header_nav">
                <span>LogIn</span>
            </a>
            <a href="{% url 'account:create' %}" class="program_header_nav">
                <span>SignUp</span>
            </a>
        {% else %}
            <a href="{% url 'account:detail' pk=user.pk %}" class="program_header_nav">
                <span>MyPage</span>
            </a>
            <a href="{% url 'account:logout' %}?next={{ request.path }}">
                <span>LogOut</span>
            </a>
        {% endif %}
    </div>
</div>