acc/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from .views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "account"
urlpatterns = [

    path("login/", LoginView.as_view(template_name="acc/login.html"), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("create/", AccountCreateView.as_view(), name='create'),
    path("detail/<int:pk>", AccountDetailView.as_view(), name='detail'),
    path("update/<int:pk>", AccountUpdateView.as_view(), name='update'),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name='delete'),
]

profileapp/urls.py
from django.urls import path

from .views import ProfileCreateView, ProfileUpdateView

app_name ="profileapp"

urlpatterns = [
    path("create/", ProfileCreateView.as_view(), name='create'),
    path("update/<int:pk>", ProfileUpdateView.as_view(), name='update'),
]

prog/program/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include("acc.urls")),
                  path('profiles/', include("profileapp.urls")),
                  path('articles/', include("articleapp.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

program/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
                  path("", ArticleListView.as_view(), name="home"),
                  path('admin/', admin.site.urls),
                  path('accounts/', include("acc.urls")),
                  path('profiles/', include("profileapp.urls")),
                  path('articles/', include("articleapp.urls")),
                  path('comments/', include("commentapp.urls")),
                  path('projects/', include("projectapp.urls")),
                  path('subscribes/', include("subscribeapp.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models


# Create your models here.
# class HelloWorld(models.Model):
#     text = models.CharField(max_length=250, null=False)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="article", null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name="article", null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to="article/", null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_created=True, null=True)

acc/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

acc/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from .decorators import account_ownership_required
from .forms import AccountUpdateForm

from django.urls import reverse, reverse_lazy

has_ownership = [account_ownership_required, login_required]


# Create your views here.


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("account:hello")
    template_name = "acc/create.html"


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = "acc/detail.html"
    paginate_by = 25

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)


@method_decorator(has_ownership, "get")
@method_decorator(has_ownership, "post")
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy("account:hello")
    template_name = "acc/update.html"


@method_decorator(has_ownership, "get")
@method_decorator(has_ownership, "post")
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy("account:login")
    template_name = "acc/delete.html"

acc/templates/acc/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Sign Up</h4>
        </div>
        <form action="{% url "account:create" %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>

    </div>

{% endblock %}

acc/templates/acc/delete.html
{% extends 'base.html' %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Quit</h4>
        </div>
        <form action="{% url "account:delete" pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

acc/templates/acc/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div>
            <p>
                {{ target_user.date_joined }}
            </p>

            {% if target_user.profile %}
                <img style="height: 12rem; width: 12rem; margin-bottom: 2rem;border-radius: 20rem; object-fit: cover;"
                     src="{{ target_user.profile.image.url }}" alt="">
                <h2 style="font-family: 'NanumSquareRoundOTFL'">
                    {{ target_user.profile.nickname }}

                    {% if target_user == user %}
                        <a class="material-icons"
                           style="box-shadow: 0 0 4px darkblue; border-radius: 10rem; padding: 0.4rem;"
                           href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                            edit
                        </a>
                    {% endif %}
                </h2>
                <h5 style="margin-bottom: 3rem;">
                    {{ target_user.profile.message }}
                </h5>
            {% else %}
                {% if target_user == user %}
                    <a href="{% url 'profileapp:create' %}">
                        <h2 style="font-family: NanumSquareRoundOTFL;">
                            Create Profile
                        </h2>
                    </a>
                {% else %}
                    <h2>
                        닉네임 미설정
                    </h2>
                {% endif %}
            {% endif %}

            {% if target_user == user %}
                <a href="{% url "account:update" pk=user.pk %}" class="material-icons"
                   style="box-shadow: 0 0 4px darkslategrey; border-radius: 10rem; padding: 0.4rem;margin: 0.4rem;">

                    settings

                </a>
                <a href="{% url "account:delete" pk=user.pk %}" class="material-icons"
                   style="box-shadow: 0 0 4px red; border-radius: 10rem; margin: 0.4rem; padding: 0.4rem;">

                    cancel

                </a>
            {% endif %}
        </div>
        <div>
            {% include "snippets/list_fragment.html"  with article_list=object_list %}
        </div>
    </div>
{% endblock %}

acc/templates/acc/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {#                {{ form }}#}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>

{% endblock %}

acc/templates/acc/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Change Info</h4>
        </div>
        <form action="{% url "account:update" pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}